name: frontier_homepage
description: "A new Flutter module project."

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.2.1
  native_shared_preferences: 2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/appimage/

  fonts:
    - family: Abacus
      fonts:
        - asset: assets/fonts/abacus.ttf
    - family: Umbrella
      fonts:
        - asset: assets/fonts/umbrella.ttf
    - family: HeartPulse
      fonts:
        - asset: assets/fonts/heart-pulse.ttf
    - family: CashPlus
      fonts:
        - asset: assets/fonts/cash-plus.ttf
    - family: HomeHeart
      fonts:
        - asset: assets/fonts/home-heart.ttf
    - family: ChartArc
      fonts:
        - asset: assets/fonts/chart-arc.ttf
    - family: ChartTimelineVariantShimmer
      fonts:
        - asset: assets/fonts/chart-timeline-variant-shimmer.ttf
    - family: HumanGreetingVariant
      fonts:
        - asset: assets/fonts/human-greeting-variant.ttf
    - family: Speedometer
      fonts:
        - asset: assets/fonts/speedometer.ttf
    - family: StarOff
      fonts:
        - asset: assets/fonts/star-off.ttf
    - family: CheckDecagram
      fonts:
        - asset: assets/fonts/check-decagram.ttf
    - family: ClockTimeTwo
      fonts:
        - asset: assets/fonts/clock-time-two.ttf
    - family: AutoFix
      fonts:
        - asset: assets/fonts/auto-fix.ttf
    - family: Ring
      fonts:
        - asset: assets/fonts/ring.ttf
    - family: CardPlus
      fonts:
        - asset: assets/fonts/card-plus.ttf
    - family: Calendar
      fonts:
        - asset: assets/fonts/calendar.ttf
    - family: Home
      fonts:
        - asset: assets/fonts/home.ttf
    - family: Question
      fonts:
        - asset: assets/fonts/question.ttf
    - family: Lock1
      fonts:
        - asset: assets/fonts/lock-1.ttf
    - family: Switches
      fonts:
        - asset: assets/fonts/switches.ttf
    - family: Location
      fonts:
        - asset: assets/fonts/location.ttf
    - family: Hospital1
      fonts:
        - asset: assets/fonts/hospital-1.ttf
    - family: LogoutVariant
      fonts:
        - asset: assets/fonts/logout-variant.ttf
    - family: Close
      fonts:
        - asset: assets/fonts/close.ttf
    - family: Magnify
      fonts:
        - asset: assets/fonts/magnify.ttf
    - family: Database
      fonts:
        - asset: assets/fonts/database.ttf
    - family: RupeesIcon
      fonts:
        - asset: assets/fonts/rupeesIcon.ttf
    - family: Optional
      fonts:
        - asset: assets/fonts/optional.ttf
    - family: Mandatory
      fonts:
        - asset: assets/fonts/Mandatory.ttf
    - family: Safe
      fonts:
        - asset: assets/fonts/safe.ttf
    - family: TimerOutline
      fonts:
        - asset: assets/fonts/timer-outline.ttf
    - family: CalendarMonth
      fonts:
        - asset: assets/fonts/calendar-month.ttf
    - family: ChatQuestionOutline
      fonts:
        - asset: assets/fonts/chat-question-outline.ttf
    - family: Edit1
      fonts:
        - asset: assets/fonts/edit1.ttf
    - family: Editing
      fonts:
        - asset: assets/fonts/editing.ttf
    - family: MoneyBag
      fonts:
        - asset: assets/fonts/money-bag.ttf
    - family: Checked
      fonts:
        - asset: assets/fonts/checked.ttf
    - family: SelfEmployedPersonRupee
      fonts:
        - asset: assets/fonts/self-employed-person-rupee.ttf
    - family: Time
      fonts:
        - asset: assets/fonts/time.ttf
    - family: GoogleForms
      fonts:
        - asset: assets/fonts/google-forms.ttf
    - family: Rgb
      fonts:
        - asset: assets/fonts/rgb.ttf
    - family: Family
      fonts:
        - asset: assets/fonts/family.ttf
    - family: Interest
      fonts:
        - asset: assets/fonts/interest.ttf
    - family: Suitcase
      fonts:
        - asset: assets/fonts/suitcase.ttf
    - family: OfficeBuildingSalariedRupee
      fonts:
        - asset: assets/fonts/office-building-Salaried-rupee-.ttf
    - family: HourglassMedium
      fonts:
        - asset: assets/fonts/HourglassMedium.ttf
    - family: Information
      fonts:
        - asset: assets/fonts/information.ttf
    - family: AlertDecagram
      fonts:
        - asset: assets/fonts/alert-decagram.ttf
    - family: HelpBox
      fonts:
        - asset: assets/fonts/help-box.ttf
    - family: CalendarPlus
      fonts:
        - asset: assets/fonts/CalendarPlus.ttf
    - family: LightbulbVariant
      fonts:
        - asset: assets/fonts/lightbulb-variant.ttf
    - family: Calculator
      fonts:
        - asset: assets/fonts/calculator.ttf
    - family: GoBackButton
      fonts:
        - asset: assets/fonts/goBackButton.ttf
    - family: ArrowRightThin
      fonts:
        - asset: assets/fonts/arrow-right-thin.ttf
    - family: StarCs
      fonts:
        - asset: assets/fonts/star_cs.ttf
    - family: ArrowHP
      fonts:
        - asset: assets/fonts/Arrow_HP.ttf
    - family: ChatHP
      fonts:
        - asset: assets/fonts/chat_HP.ttf
    - family: CloseThick
      fonts:
        - asset: assets/fonts/close-thick.ttf
    - family: NotificationArrowHP
      fonts:
        - asset: assets/fonts/notificationArrow_HP.ttf
    - family: AirplaneTakeoff
      fonts:
        - asset: assets/fonts/airplane-takeoff.ttf
    - family: QuestionRoundHP
      fonts:
        - asset: assets/fonts/question-Round_HP.ttf
    - family: MoneyPL
      fonts:
        - asset: assets/fonts/money_PL.ttf
    - family: DematCirclePL
      fonts:
        - asset: assets/fonts/dematCircle_PL.ttf
    - family: BankPL
      fonts:
        - asset: assets/fonts/bank_PL.ttf
    - family: ChartLine
      fonts:
        - asset: assets/fonts/chartLine.ttf
    - family: Money
      fonts:
        - asset: assets/fonts/money.ttf
    - family: ClockCredit
      fonts:
        - asset: assets/fonts/clock_credit.ttf
    - family: Arrow
      fonts:
        - asset: assets/fonts/arrow.ttf
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: Web
      fonts:
        - asset: assets/fonts/web.ttf
    - family: HomePL
      fonts:
        - asset: assets/fonts/Home-PL.ttf
    - family: CalendarPL
      fonts:
        - asset: assets/fonts/Calendar_PL.ttf
    - family: MoreOptionPL
      fonts:
        - asset: assets/fonts/MoreOption-PL.ttf
    - family: QrPl
      fonts:
        - asset: assets/fonts/QR-PL.ttf
    - family: MedicalPL
      fonts:
        - asset: assets/fonts/medical-PL.ttf
    - family: LogoutHP
      fonts:
        - asset: assets/fonts/Logout-HP.ttf
    - family: WarningIcon
      fonts:
        - asset: assets/fonts/warning-Icon.ttf
    - family: Businessloans
      fonts:
        - asset: assets/fonts/Businessloans.ttf
    - family: MedicalBag1
      fonts:
        - asset: assets/fonts/medical-bag1.ttf
    - family: CalendarToday
      fonts:
        - asset: assets/fonts/calendar-today.ttf
    - family: ClockWallet
      fonts:
        - asset: assets/fonts/clockWallet.ttf
    - family: ArrowUpThin
      fonts:
        - asset: assets/fonts/arrow-up-thin.ttf
    - family: Account
      fonts:
        - asset: assets/fonts/account.ttf
    - family: DhaWarningIcon
      fonts:
        - asset: assets/fonts/dha-warningIcon.ttf
    - family: DhaKeyVitalIcon
      fonts:
        - asset: assets/fonts/dha-keyVitalIcon.ttf
    - family: DhaHeart
      fonts:
        - asset: assets/fonts/dha-heart.ttf
    - family: DhaPhysiologicalicon
      fonts:
        - asset: assets/fonts/dha-physiologicalicon.ttf
    - family: EmoticonHappy
      fonts:
        - asset: assets/fonts/emoticon-happy.ttf
    - family: BankOutline
      fonts:
        - asset: assets/fonts/bank_outline.ttf
    - family: Polygon
      fonts:
        - asset: assets/fonts/polygon.ttf
    - family: ProgressCheck
      fonts:
        - asset: assets/fonts/progress_check.ttf
    - family: Pending
      fonts:
        - asset: assets/fonts/pending.ttf
    - family: MapMarker
      fonts:
        - asset: assets/fonts/map-marker.ttf
    - family: Download
      fonts:
        - asset: assets/fonts/download.ttf
    - family: Checkbox
      fonts:
        - asset: assets/fonts/checkbox.ttf
    - family: Cancelled
      fonts:
        - asset: assets/fonts/cancelled.ttf
    - family: DGSheild
      fonts:
        - asset: assets/fonts/DG_sheild.ttf
    - family: Clock
      fonts:
        - asset: assets/fonts/clock.ttf
    - family: DGGoldIconHP
      fonts:
        - asset: assets/fonts/DG_GoldIconHP.ttf
    - family: QuestionMark
      fonts:
        - asset: assets/fonts/questionMark.ttf
    - family: DHAarrow
      fonts:
        - asset: assets/fonts/DHAarrow.ttf
    - family: Polygon2
      fonts:
        - asset: assets/fonts/Polygon-2.ttf
    - family: Bell
      fonts:
        - asset: assets/fonts/bell.ttf
    - family: Uppolygon
      fonts:
        - asset: assets/fonts/uppolygon.ttf
    - family: WhiteNinjaStarLi
      fonts:
        - asset: assets/fonts/whiteNinjaStar_li.ttf
    - family: CheckStar
      fonts:
        - asset: assets/fonts/DGcheckStar.ttf
    - family: Timeclock
      fonts:
        - asset: assets/fonts/timeclock.ttf
    - family: Checkmark
      fonts:
        - asset: assets/fonts/checkmark.ttf
    - family: MoneyTickIcon
      fonts:
        - asset: assets/fonts/moneyTickIcon.ttf
    - family: LiHospitalIcon
      fonts:
        - asset: assets/fonts/li_HospitalIcon.ttf
    - family: MoneyPlus
      fonts:
        - asset: assets/fonts/MoneyPlus.ttf
    - family: LiMoneyandMan
      fonts:
        - asset: assets/fonts/li_moneyandMan.ttf
    - family: LiCriticalIllnessRider
      fonts:
        - asset: assets/fonts/li_Critical-Illness-Rider.ttf
    - family: WheelchairAccessibility
      fonts:
        - asset: assets/fonts/wheelchair-accessibility.ttf
    - family: SquareEditOutline
      fonts:
        - asset: assets/fonts/square-edit-outline.ttf
    - family: Cash
      fonts:
        - asset: assets/fonts/cash.ttf
    - family: Card
      fonts:
        - asset: assets/fonts/card.ttf
    - family: FaceWoman
      fonts:
        - asset: assets/fonts/face-woman.ttf
    - family: MotherHeart
      fonts:
        - asset: assets/fonts/mother-heart.ttf
    - family: Doctor
      fonts:
        - asset: assets/fonts/doctor.ttf
    - family: EmoticonSad
      fonts:
        - asset: assets/fonts/emoticon-sad.ttf
    - family: Water
      fonts:
        - asset: assets/fonts/water.ttf
    - family: HospitalBuilding
      fonts:
        - asset: assets/fonts/hospital-building.ttf
    - family: BottleWine
      fonts:
        - asset: assets/fonts/bottle-wine.ttf
    - family: Bomb
      fonts:
        - asset: assets/fonts/bomb.ttf
    - family: Pill
      fonts:
        - asset: assets/fonts/pill.ttf
    - family: BagSuitcase
      fonts:
        - asset: assets/fonts/bag-suitcase.ttf
    - family: Lungs
      fonts:
        - asset: assets/fonts/lungs.ttf
    - family: BloodBag
      fonts:
        - asset: assets/fonts/blood-bag.ttf
    - family: Stomach
      fonts:
        - asset: assets/fonts/stomach.ttf
    - family: StopCircle
      fonts:
        - asset: assets/fonts/stop-circle.ttf
    - family: Necklace
      fonts:
        - asset: assets/fonts/necklace.ttf
    - family: EyeSettings
      fonts:
        - asset: assets/fonts/eye-settings.ttf
    - family: FamilyTree
      fonts:
        - asset: assets/fonts/family-tree.ttf
    - family: ClockTimeThree
      fonts:
        - asset: assets/fonts/clock-time-three.ttf
    - family: Brain
      fonts:
        - asset: assets/fonts/brain.ttf
    - family: Ribbon
      fonts:
        - asset: assets/fonts/ribbon.ttf
    - family: OfficeBuilding
      fonts:
        - asset: assets/fonts/office-building.ttf
    - family: Cigar
      fonts:
        - asset: assets/fonts/cigar.ttf
    - family: DownloadMultiple
      fonts:
        - asset: assets/fonts/download-multiple.ttf
    - family: UmbrellaBeach
      fonts:
        - asset: assets/fonts/umbrella-beach.ttf
    - family: Face
      fonts:
        - asset: assets/fonts/face.ttf
    - family: Hat
      fonts:
        - asset: assets/fonts/hat.ttf
    - family: Scan
      fonts:
        - asset: assets/fonts/scan.ttf
    - family: Sign
      fonts:
        - asset: assets/fonts/sign.ttf
    - family: ViewList
      fonts:
        - asset: assets/fonts/view-list.ttf
    - family: FaceMan
      fonts:
        - asset: assets/fonts/face-man.ttf
    - family: FileDocumentOutline
      fonts:
        - asset: assets/fonts/file-document-outline.ttf
    - family: OrderBoolAscendingVariant
      fonts:
        - asset: assets/fonts/order-bool-ascending-variant.ttf
    - family: CardBulletedOutline
      fonts:
        - asset: assets/fonts/card-bulleted-outline.ttf
    - family: ShieldRefreshOutline
      fonts:
        - asset: assets/fonts/shield-refresh-outline.ttf
    - family: Transfer
      fonts:
        - asset: assets/fonts/transfer.ttf
    - family: CashRefund
      fonts:
        - asset: assets/fonts/cash-refund.ttf
    - family: BankTransfer
      fonts:
        - asset: assets/fonts/bank-transfer.ttf
    - family: PlusCircle
      fonts:
        - asset: assets/fonts/plus-circle.ttf
    - family: Pdf
      fonts:
        - asset: assets/fonts/pdf.ttf
    - family: DescendingSorting
      fonts:
        - asset: assets/fonts/Descending-Sorting.ttf
    - family: ClockTimeTwoOutline
      fonts:
        - asset: assets/fonts/clock-time-two-outline.ttf
    - family: AnekLatinBold
      fonts:
        - asset: assets/fonts/AnekLatin-Bold.ttf
    - family: AnekLatinRegular
      fonts:
        - asset: assets/fonts/AnekLatin-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.example.frontier_homepage
    iosBundleIdentifier: com.example.frontierHomepage
